Repository epam/ai-dial-core, pull requests merged in 2024-10, with the labels that each got.

#501 fix: add configurationEndpoint to application features
  README.md
Labels: documentation

#510 feat: added span name processor
  src/main/java/com/epam/aidial/core/controller/ControllerSelector.java
  src/main/java/com/epam/aidial/core/util/RegexUtil.java
  src/main/java/com/epam/aidial/core/util/SpanUtil.java
  src/test/java/com/epam/aidial/core/util/RegexUtilTest.java
Labels: enhancement

#514 feat: allowed HEAD HTTP method
  src/main/java/com/epam/aidial/core/Proxy.java
  src/test/java/com/epam/aidial/core/ResourceBaseTest.java
  src/test/java/com/epam/aidial/core/RouteApiTest.java
  src/test/resources/aidial.config.json
Labels: enhancement

#516 feat: Mechanism to make a deployment unavailable to any role #515
  src/main/java/com/epam/aidial/core/config/Deployment.java
  src/main/java/com/epam/aidial/core/config/Route.java
  src/main/java/com/epam/aidial/core/controller/DeploymentController.java
  src/main/java/com/epam/aidial/core/controller/RouteController.java
  src/main/java/com/epam/aidial/core/limiter/RateLimiter.java
  src/main/java/com/epam/aidial/core/service/ApplicationService.java
  src/test/java/com/epam/aidial/core/CustomApplicationApiTest.java
  src/test/java/com/epam/aidial/core/RouteApiTest.java
  src/test/java/com/epam/aidial/core/controller/DeploymentControllerTest.java
  src/test/resources/aidial.config.json
Labels: enhancement

#543 fix: span names
  server/src/main/java/com/epam/aidial/core/server/security/IdentityProvider.java
Labels: bug

#550 feat: store http headers through an interceptors invocation chain
  server/src/main/java/com/epam/aidial/core/server/ProxyContext.java
  server/src/main/java/com/epam/aidial/core/server/data/ApiKeyData.java
  server/src/main/java/com/epam/aidial/core/server/log/GfLogStore.java
Labels: enhancement
